name: 'Install minepkg CLI'
description: 'Installs the minepkg CLI, so you can use it for custom builds'
author: 'minepkg'
inputs:
  version:
    description: 'The CLI version to install'
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
